name: Minify and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install html-minifier
        run: npm install -g html-minifier terser clean-css-cli
      
      - name: Minify HTML
        run: |
          mkdir -p dist
          find . -name "*.html" -not -path "./dist/*" -exec sh -c '
            for f do
              out="dist/$f"
              mkdir -p "$(dirname "$out")"
              html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true "$f" -o "$out"
            done
          ' sh {} +
      
      - name: Minify JS
        run: |
          find . -name "*.js" -not -path "./dist/*" -exec sh -c '
            for f do
              out="dist/$f"
              mkdir -p "$(dirname "$out")"
              terser "$f" -o "$out" --compress --mangle
            done
          ' sh {} +
      
      - name: Minify CSS
        run: |
          find . -name "*.css" -not -path "./dist/*" -exec sh -c '
            for f do
              out="dist/$f"
              mkdir -p "$(dirname "$out")"
              cleancss "$f" -o "$out"
            done
          ' sh {} +

      - name: Copy other files (non-minified)
        run: |
          find . -type f -not -path "./dist/*" -exec sh -c '
            for f do
              out="dist/$f"
              mkdir -p "$(dirname "$out")"
              cp "$f" "$out"
            done
          ' sh {} +
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
