name: Minify and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install html-minifier
        run: npm install -g html-minifier terser clean-css-cli
      
      - name: Minify HTML
        run: |
          mkdir dist
          for file in $(find . -name '*.html'); do
            html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true "$file" -o "dist/$file"
          done
      
      - name: Minify JS
        run: |
          for file in $(find . -name '*.js'); do
            terser "$file" -o "dist/$file" --compress --mangle
          done
      
      - name: Minify CSS
        run: |
          for file in $(find . -name '*.css'); do
            cleancss "$file" -o "dist/$file"
          done
      
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB }}
          publish_dir: ./dist